export const production = {
	NEXT_PUBLIC_SANITY_PROJECT_ID: "fsymw50k",
	NEXT_PUBLIC_SANITY_DATASET: "production",
	RESEND_API_KEY: "re_XcCFpUKf_LLfn4LtpHYRjutTQifVjKpc2",
	SANITY_WRITE_TOKEN:
		"skKvfmq7AzPiVRZd0T3PWNj4rNz6NV4kncAOTkLwrd8oab8cU5jQ6es3LtGWcl0qQAxrIiD7OnGRMvQRyckLeqWbXMcbRijOltAffyVtIFWPbtl7Fau5FOKPJWt3XF4zghciMSKFcJFR03I8JVF86uGAnQUKDBm6dbKS4H4P30gGoigiVbtR",
};
export const development = {
	NEXT_PUBLIC_SANITY_PROJECT_ID: "fsymw50k",
	NEXT_PUBLIC_SANITY_DATASET: "production",
	RESEND_API_KEY: "re_XcCFpUKf_LLfn4LtpHYRjutTQifVjKpc2",
	SANITY_WRITE_TOKEN:
		"skKvfmq7AzPiVRZd0T3PWNj4rNz6NV4kncAOTkLwrd8oab8cU5jQ6es3LtGWcl0qQAxrIiD7OnGRMvQRyckLeqWbXMcbRijOltAffyVtIFWPbtl7Fau5FOKPJWt3XF4zghciMSKFcJFR03I8JVF86uGAnQUKDBm6dbKS4H4P30gGoigiVbtR",
};
export const test = {
	NEXT_PUBLIC_SANITY_PROJECT_ID: "fsymw50k",
	NEXT_PUBLIC_SANITY_DATASET: "production",
	RESEND_API_KEY: "re_XcCFpUKf_LLfn4LtpHYRjutTQifVjKpc2",
	SANITY_WRITE_TOKEN:
		"skKvfmq7AzPiVRZd0T3PWNj4rNz6NV4kncAOTkLwrd8oab8cU5jQ6es3LtGWcl0qQAxrIiD7OnGRMvQRyckLeqWbXMcbRijOltAffyVtIFWPbtl7Fau5FOKPJWt3XF4zghciMSKFcJFR03I8JVF86uGAnQUKDBm6dbKS4H4P30gGoigiVbtR",
};
